# Package Overview
package_name: bikeshare_model

# Data Files
training_data_file: bike-sharing-dataset.csv

test_data_file: test.csv

# Variables
# The variable we are attempting to predict (cnt)
target: cnt


pipeline_name: bikeshare_model
pipeline_save_file: bikeshare__model_output_v

features:
  - dteday
  - season
  - hr
  - holiday
  - weekday
  - workingday
  - weathersit
  - temp
  - atemp
  - hum
  - windspeed
  - casual
  - registered
  - yr
  - mnth



# Features inside processing pipeline
weekday_var : weekday
weathersit_var : weathersit
yr_var : yr
mnth_var : mnth
season_var : season
holiday_var : holiday
workingday_var : workingday
hr_var : hr
hum_var : hum
windspeed_var : windspeed


yr_mappings:
  2011: 0
  2012: 1

mnth_mappings:
  January: 0
  February: 1
  December: 2
  March: 3
  November: 4
  April: 5
  October: 6
  May: 7
  September: 8
  June: 9
  July: 10
  August: 11

season_mappings:
  spring: 0
  winter: 1
  summer: 2
  fall: 3

holiday_mappings:
  Yes: 0
  No: 1

workingday_mappings:
  Yes: 1
  No: 0

hr_mappings:
  4am: 0
  3am: 1
  5am: 2
  2am: 3
  1am: 4
  12am: 5
  6am: 6
  11pm: 7
  10pm: 8
  10am: 9
  9pm: 10
  11am: 11
  7am: 12
  9am: 13
  8pm: 14
  2pm: 15
  1pm: 16
  12pm: 17
  3pm: 18
  4pm: 19
  7pm: 20
  8am: 21
  6pm: 22
  5pm: 23

weathersit_mappings:
  Heavy Rain: 0
  Light Rain: 1
  Mist: 2
  Clear: 3

#embarked_var: Embarked  # first imputatation , then --> Mappeing
#
#gender_var: Sex
#
#title_var: Title
#
#age_var: Age
#
#gender_mappings:
#  female: 0
#  male: 1
#
#embarked_mappings:
#  S: 0
#  C: 1
#  Q: 2
#
#title_mappings:
#  Mrs: 4
#  Master: 3
#  Miss: 2
#  Mr: 1
#  Other: 0

  
# set train/test split
test_size: 0.20
# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 100
max_depth: 10
