name : CD pipeline

# only trigger when the ci piplne is compmleted

on:
  workflow_run:
    workflows: ['Push a Docker Image']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name : Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run : sudo docker pull $DOCKER_USER/bikeshare-fastapi:latest
      - name : Delete old Docker container
        run : sudo docker rm -f bikeshare-fastapi-container || true
      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run : sudo docker run -d -p 8000:8000 --name bikeshare-fastapi-container $DOCKER_USER/bikeshare-fastapi